services:
  _defaults:
    autowire: true
    autoconfigure: true

  Infrastructure\Symfony\Controller\HelloController:
    tags: ['controller.service_arguments']

  Infrastructure\Symfony\Controller\ApiController:
    tags: ['controller.service_arguments']

  Infrastructure\Symfony\Controller\TaskController:
    tags: ['controller.service_arguments']

  Infrastructure\Symfony\Controller\MetricsController:
    tags: ['controller.service_arguments']

  Application\AddTaskUseCase: ~

  Domain\TaskRepository:
    class: Infrastructure\Persistence\InMemoryTaskRepository
