framework:
    cache:
        prefix_seed: api_template_php
        app: cache.adapter.apcu
        system: cache.adapter.apcu

        pools:
            cache.app:
                adapter: cache.adapter.apcu
                default_lifetime: 3600

            cache.router:
                adapter: cache.adapter.filesystem
                default_lifetime: 86400

            cache.validator:
                adapter: cache.adapter.apcu
                default_lifetime: 3600
