framework:
  secret: '%env(APP_SECRET)%'

  router:
    utf8: true
    strict_requirements: ~
    resource: '%kernel.project_dir%/config/routes.yaml'

  handle_all_throwables: true
  php_errors:
    log: true
  error_controller: 'error_controller'

  session:
    enabled: false

  http_cache: true
