framework:
  secret: '%env(APP_SECRET)%'
  router:
    utf8: true
    enable_attributes: true   # <— LA LIGNE MAGIQUE QUI MANQUAIT DEPUIS LE DÉBUT
  handle_all_throwables: true
  annotations: true
  php_errors:
    log: true
  error_controller: 'error_controller'
