# config/packages/routing.yaml
framework:
  router:
    resource: '%kernel.project_dir%/config/routes.yaml'
    type: yaml

when@dev:
  framework:
    router:
      strict_requirements: null

# FORCER le chargement de config/routes.yaml (c’est ÇA qui manquait)
imports:
  - { resource: '../routes.yaml' }